name: taylord_portfolio
description: "An AI portfolio generating assistant."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.0

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  path_provider: ^2.1.3
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  path: ^1.9.0
  pdf: ^3.11.0
  file_picker: ^8.0.6
  syncfusion_flutter_pdf: ^26.1.40
  process_run: ^1.0.0+1
  archive: ^3.6.1
  syncfusion_flutter_pdfviewer: ^26.1.41
  uri: ^1.0.0
  url_launcher: ^6.3.0
  open_file: ^3.5.3
  accordion: ^2.6.0
  get: ^4.6.6
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^26.2.14
  graphic: ^2.5.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env